//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGenesis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdProcess()
        {
            this.AdProcessDetail = new HashSet<AdProcessDetail>();
        }
    
        public long AdProcessId { get; set; }
        public int UserId { get; set; }
        public int AdProcessTypeId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AdProcessType AdProcessType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdProcessDetail> AdProcessDetail { get; set; }
        public virtual User User { get; set; }
    }
}
