//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGenesis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdProcessDetail
    {
        public int RowId { get; set; }
        public long AdProcessId { get; set; }
        public int AdProcessTypeDetailId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AdProcess AdProcess { get; set; }
        public virtual AdProcessTypeDetail AdProcessTypeDetail { get; set; }
    }
}
