//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGenesis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigReward
    {
        public decimal CurrStandarRewardPerAdTether { get; set; }
        public decimal CurrStandarRewardPerAdDalion { get; set; }
        public int MinTimeStandarReward { get; set; }
        public decimal MinWithdrawalAmountTether { get; set; }
        public decimal MinWithdrawalAmountDalion { get; set; }
        public double RewardByReferredPercent { get; set; }
    }
}
