//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGenesis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CryptoGenesisEntities : DbContext
    {
        public CryptoGenesisEntities()
            : base("name=CryptoGenesisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdProcess> AdProcess { get; set; }
        public virtual DbSet<AdProcessType> AdProcessType { get; set; }
        public virtual DbSet<AdProcessTypeDetail> AdProcessTypeDetail { get; set; }
        public virtual DbSet<SessionToken> SessionToken { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Wallet> Wallet { get; set; }
        public virtual DbSet<Withdrawal> Withdrawal { get; set; }
        public virtual DbSet<AdProcessDetail> AdProcessDetail { get; set; }
        public virtual DbSet<ConfigReward> ConfigReward { get; set; }
        public virtual DbSet<ConfigGeneral> ConfigGeneral { get; set; }
    }
}
