//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoGenesis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public int WithdrawalId { get; set; }
        public int WalletId { get; set; }
        public string CurrencyId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Wallet Wallet { get; set; }
    }
}
